/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import static java.lang.Double.parseDouble;
import javax.swing.JOptionPane;

/**
 *
 * @author Sulain ADONNEKPO
 */
public class Convertisseur extends javax.swing.JFrame {

    /**
     * Creates new form Convertisseur
     */
    public Convertisseur() {
        initComponents();
    }

    public double dMonFranc,dFrancMon,dMonEuro,dEuroMon,dMonDol,dDolMon;
            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        TextGauche = new javax.swing.JTextField();
        TextDroite = new javax.swing.JTextField();
        Convert = new javax.swing.JButton();
        jQuit = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        Adding = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel2MouseMoved(evt);
            }
        });

        TextGauche.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        TextGauche.setBorder(null);

        TextDroite.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        TextDroite.setBorder(null);

        Convert.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        Convert.setText("Convertir");
        Convert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConvertActionPerformed(evt);
            }
        });

        jQuit.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        jQuit.setText("Quitter");
        jQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQuitActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Franc CFA", "Euro", "Dollar US" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Euro", "Franc CFA", "Dollar US" }));

        jLabel1.setBackground(new java.awt.Color(0, 102, 102));
        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Convertisseur");

        Adding.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        Adding.setText("Ajouter monnaie");
        Adding.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TextGauche)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jQuit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.TRAILING, 0, 114, Short.MAX_VALUE)
                            .addComponent(TextDroite, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(Adding)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(Convert)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextGauche, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextDroite, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Convert)
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Adding)
                    .addComponent(jQuit))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public String LaValMon;
    
    private void ConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConvertActionPerformed
        // TODO add your handling code here:
        String SelectionG,SelectionD,val;
        SelectionG=(String) jComboBox1.getSelectedItem();
        SelectionD=(String) jComboBox2.getSelectedItem();
        double VG,VD;
        double dEuroFranc=657, dFrancEuro=0.0015, dFrancDol=0.0017,dDolFranc=601.21,dEuroDol=1.10,dDolEuro=0.91;
        /*dMonEuro=second.dValE;
        dMonFranc=second.dValF;
        dMonDol=second.dValD;
        dDolMon=(1/dMonDol);
        dFrancMon=(1/dMonFranc);
        dEuroMon=(1/dMonEuro);*/
        
        if(TextGauche.getText().isEmpty() && TextDroite.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Un des champs est vide réessayer");
        }
        if(!TextGauche.getText().isEmpty() && !TextDroite.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Les deux champs sont pleins on a besoin que d'un des champs");
        }
        if(SelectionG.equals(SelectionD)){
            JOptionPane.showMessageDialog(this,"Les selections des Monnaies doivent être differentes");
        }
        
        
        if(TextGauche.getText().isEmpty() && !TextDroite.getText().isEmpty()){
            if(SelectionG.equals("Franc CFA")){
                if(SelectionD.equals("Euro")){
                  VD=parseDouble(TextDroite.getText());
                  VD*=dEuroFranc;
                  val=""+VD;
                  TextGauche.setText(val);
                  TextGauche.setCaretPosition(0);
                }
                if(SelectionD.equals("Dollar US")){
                  VD=parseDouble(TextDroite.getText());
                  VD*=dDolFranc;
                  val=""+VD;
                  TextGauche.setText(val);
                  TextGauche.setCaretPosition(0);
                }
                if(SelectionD.equals(LaValMon)){
                  VD=parseDouble(TextDroite.getText());
                  VD*=dMonFranc;
                  val=""+VD;
                  TextGauche.setText(val);
                  TextGauche.setCaretPosition(0);
                }
                
            }
            if(SelectionG.equals("Euro")){
                if(SelectionD.equals("Franc CFA")){
                  VD=parseDouble(TextDroite.getText());
                  VD*=dFrancEuro;
                  val=""+VD;
                  TextGauche.setText(val);
                  TextGauche.setCaretPosition(0);
                }
                if(SelectionD.equals("Dollar US")){
                  VD=parseDouble(TextDroite.getText());
                  VD*=dDolEuro;
                  val=""+VD;
                  TextGauche.setText(val);
                  TextGauche.setCaretPosition(0);
                }
                if(SelectionD.equals(LaValMon)){
                  VD=parseDouble(TextDroite.getText());
                  VD*=dMonEuro;
                  val=""+VD;
                  TextGauche.setText(val);
                  TextGauche.setCaretPosition(0);
                }
            }
            if(SelectionG.equals("Dollar US")){
                if(SelectionD.equals("Euro")){
                  VD=parseDouble(TextDroite.getText());
                  VD*=dEuroDol;
                  val=""+VD;
                  TextGauche.setText(val);
                  TextGauche.setCaretPosition(0);
                }
                if(SelectionD.equals("Franc CFA")){
                  VD=parseDouble(TextDroite.getText());
                  VD*=dFrancDol;
                  val=""+VD;
                  TextGauche.setText(val);
                  TextGauche.setCaretPosition(0);
                }
                if(SelectionD.equals(LaValMon)){
                  VD=parseDouble(TextDroite.getText());
                  VD*=dMonDol;
                  val=""+VD;
                  TextGauche.setText(val);
                  TextGauche.setCaretPosition(0);
                }
            }
            if(SelectionG.equals(LaValMon)){
                if(SelectionD.equals("Euro")){
                  VD=parseDouble(TextDroite.getText());
                  VD*=dEuroMon;
                  val=""+VD;
                  TextGauche.setText(val);
                  TextGauche.setCaretPosition(0);
                }
                if(SelectionD.equals("Franc CFA")){
                  VD=parseDouble(TextDroite.getText());
                  VD*=dFrancMon;
                  val=""+VD;
                  TextGauche.setText(val);
                  TextGauche.setCaretPosition(0);
                }
                if(SelectionD.equals("Dollar US")){
                  VD=parseDouble(TextDroite.getText());
                  VD*=dDolMon;
                  val=""+VD;
                  TextGauche.setText(val);
                  TextGauche.setCaretPosition(0);
                }
            }
        }
        
        if(!TextGauche.getText().isEmpty() && TextDroite.getText().isEmpty()){
            if(SelectionG.equals("Franc CFA")){
                if(SelectionD.equals("Euro")){
                  VG=parseDouble(TextGauche.getText());
                  VG*=dFrancEuro;
                  val=""+VG;
                  TextDroite.setText(val);
                  TextDroite.setCaretPosition(0);
                }
                if(SelectionD.equals("Dollar US")){
                  VG=parseDouble(TextGauche.getText());
                  VG*=dFrancDol;
                  val=""+VG;
                  TextDroite.setText(val);
                  TextDroite.setCaretPosition(0);
                }
                if(SelectionD.equals(LaValMon)){
                  VG=parseDouble(TextGauche.getText());
                  VG*=dFrancMon;
                  val=""+VG;
                  TextDroite.setText(val);
                  TextDroite.setCaretPosition(0);
                }
            }
            if(SelectionG.equals("Euro")){
                if(SelectionD.equals("Franc CFA")){
                  VG=parseDouble(TextGauche.getText());
                  VG*=dEuroFranc;
                  val=""+VG;
                  TextDroite.setText(val);
                  TextDroite.setCaretPosition(0);
                }
                if(SelectionD.equals("Dollar US")){
                  VG=parseDouble(TextGauche.getText());
                  VG*=dEuroDol;
                  val=""+VG;
                  TextDroite.setText(val);
                  TextDroite.setCaretPosition(0);
                }
                if(SelectionD.equals(LaValMon)){
                  VG=parseDouble(TextGauche.getText());
                  VG*=dEuroMon;
                  val=""+VG;
                  TextDroite.setText(val);
                  TextDroite.setCaretPosition(0);
                }
            }
            if(SelectionG.equals("Dollar US")){
                if(SelectionD.equals("Euro")){
                  VG=parseDouble(TextGauche.getText());
                  VG*=dDolEuro;
                  val=""+VG;
                  TextDroite.setText(val);
                  TextDroite.setCaretPosition(0);
                }
                if(SelectionD.equals("Franc CFA")){
                  VG=parseDouble(TextGauche.getText());
                  VG*=dDolFranc;
                  val=""+VG;
                  TextDroite.setText(val);
                  TextDroite.setCaretPosition(0);
                }
                if(SelectionD.equals(LaValMon)){
                  VG=parseDouble(TextGauche.getText());
                  VG*=dDolMon;
                  val=""+VG;
                  TextDroite.setText(val);
                  TextDroite.setCaretPosition(0);
                }
            }
            if(SelectionG.equals(LaValMon)){
                if(SelectionD.equals("Euro")){
                  VG=parseDouble(TextGauche.getText());
                  VG*=dMonEuro;
                  val=""+VG;
                  TextDroite.setText(val);
                  TextDroite.setCaretPosition(0);
                }
                if(SelectionD.equals("Franc CFA")){
                  VG=parseDouble(TextGauche.getText());
                  VG*=dMonFranc;
                  val=""+VG;
                  TextDroite.setText(val);
                  TextDroite.setCaretPosition(0);
                }
                if(SelectionD.equals("Dollar US")){
                  VG=parseDouble(TextGauche.getText());
                  VG*=dMonDol;
                  val=""+VG;
                  TextDroite.setText(val);
                  TextDroite.setCaretPosition(0);
                }
            }
        }
        
     /*String Double=second.getMonnaie();
     JOptionPane.showMessageDialog(this, Double);
     jComboBox1.addItem(Double);*/
    }//GEN-LAST:event_ConvertActionPerformed

    private void jQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQuitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jQuitActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed
    AjoutElmt second = new AjoutElmt();
    private void AddingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddingActionPerformed
        // TODO add your handling code here:
        second.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AddingActionPerformed

    private void jPanel2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MouseMoved
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Convertisseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Convertisseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Convertisseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Convertisseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Convertisseur().setVisible(true);
            }
        });
    }
    
    public javax.swing.JComboBox<String> getComb1(){
        return this.jComboBox1;
    }
    public javax.swing.JComboBox<String> getComb2(){
        return this.jComboBox2;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Adding;
    private javax.swing.JButton Convert;
    private javax.swing.JTextField TextDroite;
    private javax.swing.JTextField TextGauche;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jQuit;
    // End of variables declaration//GEN-END:variables
}
